# for local development
version: '3.7'
services:
  frontend:
    build:
      context: .
      target: 'develop-stage'
    ports:
      - 8085:8080
    volumes:
      - '.:/app'
      - '/app/node_modules'
#    command: /bin/sh -c "yarn serve"
    tty: true
